# -*- coding: utf-8 -*-
"""chipotle filtring adn sorting Data Pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18hflir7eg70R049bpcJLHflC9-OA_5Pr

# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries
"""

import pandas as pd
import numpy as np

"""### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.
"""

url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
chipo = pd.read_csv(url, sep = "\t")

"""### Step 4. How many products cost more than $10.00?"""

prices = [float(value[1 : -1]) for value in chipo.item_price]
chipo["item_price"] > 10.00

"""### Step 5. What is the price of each item?
###### print a data frame with only two columns item_name and item_price
"""

chipo["item_name"]
chipo["item_price"]

"""### Step 6. Sort by the name of the item"""

chipo["item_name"].sort_index

"""### Step 7. What was the quantity of the most expensive item ordered?"""

chipo["quantity"].value_counts

"""### Step 8. How many times was a Veggie Salad Bowl ordered?"""



"""### Step 9. How many times did someone order more than one Canned Soda?"""

