# -*- coding: utf-8 -*-
"""Filtering and Sorting Data Pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10nbEh1F1Zal_t2UGzm7eZO5dG2hgoHVJ

# Ex2 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.

### Step 1. Import the necessary libraries
"""

import pandas as pd
import numpy as np

"""### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/02_Filtering_%26_Sorting/Euro12/Euro_2012_stats_TEAM.csv).

### Step 3. Assign it to a variable called euro12.
"""

url = "https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/02_Filtering_%26_Sorting/Euro12/Euro_2012_stats_TEAM.csv"
eruo12 = pd.read_csv(url, sep = ",")

"""### Step 4. Select only the Goal column."""

goal = eruo12["Goals"]
goal

"""### Step 5. How many team participated in the Euro2012?"""

teams = eruo12["Team"]
teams

"""### Step 6. What is the number of columns in the dataset?"""

columns = eruo12.shape[1]
columns

"""### Step 7. View only the columns Team, Yellow Cards and Red Cards and assign them to a dataframe called discipline"""

discipline = eruo12[["Team", "Yellow Cards", "Red Cards"]]
discipline

"""### Step 8. Sort the teams by Red Cards, then to Yellow Cards"""

discipline_sorted = discipline.sort_values(["Red Cards", "Yellow Cards"], ascending = False)
discipline_sorted

"""### Step 9. Calculate the mean Yellow Cards given per Team"""

yellow_cards = round(discipline["Yellow Cards"].mean())
yellow_cards

"""### Step 10. Filter teams that scored more than 6 goals"""

more_6 = eruo12[eruo12["Goals"] > 6]
more_6

"""### Step 11. Select the teams that start with G"""

teams_G = eruo12[eruo12["Team"].str.startswith("G")]
teams_G

"""### Step 12. Select the first 7 columns"""

columnes = eruo12[eruo12.columns[: 7]]
columnes

"""### Step 13. Select all columns except the last 3."""

columnes_except = eruo12[eruo12.columns[: -3]]
columnes_except

"""### Step 14. Present only the Shooting Accuracy from England, Italy and Russia"""

accuracy = eruo12.loc[eruo12["Team"].isin(["England", "Italy", "Russia"]), ["Team", "Shooting Accuracy"]]
accuracy

eruo12.loc[3 : 7]

