# -*- coding: utf-8 -*-
"""Getting Financial Data - Pandas Datareader and  Time series(Not finished)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b6ewyzZDdGQ-ifn9_vSaoK5eFj0UTu2r

# Getting Financial Data - Pandas Datareader

### Introduction:

This time you will get data from a website.


### Step 1. Import the necessary libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
import pandas_datareader as pdr

"""### Step 2. Create your time range (start and end variables). The start date should be 01/01/2015 and the end should today (whatever your today is)."""

start_date = datetime(2015, 1, 1)
end_date = datetime.today()

"""### Step 3. Get an API key for one of the APIs that are supported by Pandas Datareader, preferably for AlphaVantage.

If you do not have an API key for any of the supported APIs, it is easiest to get one for [AlphaVantage](https://www.alphavantage.co/support/#api-key). (Note that the API key is shown directly after the signup. You do *not* receive it via e-mail.)

(For a full list of the APIs that are supported by Pandas Datareader, [see here](https://pydata.github.io/pandas-datareader/readers/index.html). As the APIs are provided by third parties, this list may change.)

### Step 4. Use Pandas Datarader to read the daily time series for the Apple stock (ticker symbol AAPL) between 01/01/2015 and today, assign it to df_apple and print it.
"""

API_k = "2OQ4S3E7I4091R30"
apple = pdr.DataReader("AAPL", "av-daily", start = start_date, end = end_date, api_key = API_k)
apple

"""### Step 5. Add a new column "stock" to the dataframe and add the ticker symbol"""

apple["stock"] = "AAPL"
apple

"""### Step 6. Repeat the two previous steps for a few other stocks, always creating a new dataframe: Tesla, IBM and Microsoft. (Ticker symbols TSLA, IBM and MSFT.)"""

Tesla = pdr.DataReader("TSLA", "av-daily", start = start_date, end = end_date, api_key = API_k)
Tesla["stock"] = "TSLA"
Tesla

IBM = pdr.DataReader("IBM", "av-daily", start = start_date, end = end_date, api_key = API_k)
IBM["stock"] = "IBM"
IBM

Microsoft = pdr.DataReader("MSFT", "av-daily", start = start_date, end = end_date, api_key = API_k)
Microsoft["stock"] = "MSFT"
Microsoft

"""### Step 7. Combine the four separate dataFrames into one combined dataFrame df that holds the information for all four stocks"""

df = pd.concat([Tesla, IBM, Microsoft])
df

"""### Step 8. Shift the stock column into the index (making it a multi-level index consisting of the ticker symbol and the date)."""

df = df.set_index(["stock", df.index])
df

"""### Step 7. Create a dataFrame called vol, with the volume values."""

#vol = pd.DataFrame(df["volume"])
#vol
vol = df[["volume"]]
vol

"""### Step 8. Aggregate the data of volume to weekly.
Hint: Be careful to not sum data from the same week of 2015 and other years.
"""

vol_weekly = vol.groupby(["stock", pd.Grouper(freq = "W-MON")]).sum()
vol_weekly

"""### Step 9. Find all the volume traded in the year of 2015"""

year_2015 = vol.loc[vol.index.get_level_values("Date").year == 2015].groupby("stock").sum()
year_2015

