# -*- coding: utf-8 -*-
"""GroupBy Alcohol Pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r86GlQ2ZIEkz-g7Q5KY1G2iNneNJ0FXH

# Ex - GroupBy

### Introduction:

GroupBy can be summarized as Split-Apply-Combine.

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

Check out this [Diagram](http://i.imgur.com/yjNkiwL.png)  
### Step 1. Import the necessary libraries
"""

import pandas as pd
import numpy as np

"""### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv).

### Step 3. Assign it to a variable called drinks.
"""

url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv"
drinks = pd.read_csv(url, sep  = ",")

"""### Step 4. Which continent drinks more beer on average?"""

beer_continent = drinks.groupby("continent")["beer_servings"].mean()
beer_continent

"""### Step 5. For each continent print the statistics for wine consumption."""

wine = drinks.groupby("continent")["wine_servings"].describe()
wine

"""### Step 6. Print the mean alcohol consumption per continent for every column"""

alcohol = drinks.groupby("continent")["total_litres_of_pure_alcohol"].mean()
alcohol

"""### Step 7. Print the median alcohol consumption per continent for every column"""

consumption = drinks.groupby("continent")["total_litres_of_pure_alcohol"].median()
consumption

"""### Step 8. Print the mean, min and max values for spirit consumption.
#### This time output a DataFrame
"""

statistics = drinks.groupby("continent")["spirit_servings"].agg(["mean", "min", "max"])
statistics

