# -*- coding: utf-8 -*-
"""Housing Market Pandas and Numpy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PZyJWV3NDvNMWnS7UCA6DPrPgn7cjELw

# Housing Market

### Introduction:

This time we will create our own dataset with fictional numbers to describe a house market. As we are going to create random data don't try to reason of the numbers.

### Step 1. Import the necessary libraries
"""

import pandas as pd
import numpy as np

"""### Step 2. Create 3 differents Series, each of length 100, as follows:
1. The first a random number from 1 to 4
2. The second a random number from 1 to 3
3. The third a random number from 10,000 to 30,000
"""

list1 = pd.Series(np.random.randint(1, 5, size = 100))
list2 = pd.Series(np.random.randint(1, 4, size = 100))
list3 = pd.Series(np.random.randint(10000, 30001, size = 100))

"""### Step 3. Let's create a DataFrame by joinning the Series by column"""

df = pd.concat([list1, list2, list3], axis = 1)
df

"""### Step 4. Change the name of the columns to bedrs, bathrs, price_sqr_meter"""

df.columns = ["bedrs", "bathrs", "price_sqr_meter"]

"""### Step 5. Create a one column DataFrame with the values of the 3 Series and assign it to 'bigcolumn'"""

bigcolumn = pd.concat([list1, list2, list3], axis = 0).to_frame()
bigcolumn

"""### Step 6. Oops, it seems it is going only until index 99. Is it true?"""

bigcolumn.index.max()

"""### Step 7. Reindex the DataFrame so it goes from 0 to 299"""

bigcolumn.reset_index(drop = True, inplace = True)
bigcolumn

