# -*- coding: utf-8 -*-
"""MPG Cars Pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rUEvlru3E8C8tyFiiG-UEKkjhj05glSL

# MPG Cars

### Introduction:

The following exercise utilizes data from [UC Irvine Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/Auto+MPG)

### Step 1. Import the necessary libraries
"""

import pandas as pd
import numpy as np

"""### Step 2. Import the first dataset [cars1](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv) and [cars2](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv).

### Step 3. Assign each to a variable called cars1 and cars2
"""

url1 = "https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv"
url2 = "https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv"
cars1 = pd.read_csv(url1, sep = ",")
cars2 = pd.read_csv(url2, sep = ",")

"""### Step 4. Oops, it seems our first dataset has some unnamed blank columns, fix cars1"""

cars1 = cars1.dropna(axis = 1)
cars1

"""### Step 5. What is the number of observations in each dataset?"""

len(cars1)
len(cars2)

"""### Step 6. Join cars1 and cars2 into a single DataFrame called cars"""

cars = pd.concat([cars1, cars2], ignore_index = True)
cars

"""### Step 7. Oops, there is a column missing, called owners. Create a random number Series from 15,000 to 73,000."""

owners = np.random.randint(15000, 73000, size = len(cars))
owners

"""### Step 8. Add the column owners to cars"""

cars["owners"] = owners

