# -*- coding: utf-8 -*-
"""Pokemon Series

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WT-LTevzkP_X8Nwxznkd81e9REsE5z7D

# Pokemon

### Introduction:

This time you will create the data.



### Step 1. Import the necessary libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""### Step 2. Create a data dictionary that looks like the DataFrame below"""

dictionary = {"evolution": ["lvysaur", "Charmeleon", "Wartortle", "Metapod"], "name": ["Bulbasaur", "Charmander", "Squirtle", "Caterpie"], "pokedex": ["yes", "no", "yes", "no"], "type": ["grass", "fire", "water", "bug"], "hp": [45, 39, 44, 45]}

"""### Step 3. Assign it to a variable called pokemon"""

pokemon = pd.DataFrame(dictionary)
pokemon

"""### Step 4. Ops...it seems the DataFrame columns are in alphabetical order. Place  the order of the columns as name, type, hp, evolution, pokedex"""

pokemon = pokemon[["name", "type", "hp", "evolution", "pokedex"]]
pokemon

"""### Step 5. Add another column called place, and insert what you have in mind."""

pokemon["place"] = ["Bulzaria", "Chamnderia", "Squyrtelia", "Caterpilia"]
pokemon

"""### Step 6. Present the type of each column"""

pokemon.dtypes

"""### BONUS: Create your own question and answer it."""

plt.figure(figsize = (12, 5))
sns.scatterplot(x = "type", y = "hp", hue = "pokedex", data = pokemon, s = 100)
plt.show()

