# -*- coding: utf-8 -*-
"""Scores Pandas visiulization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1495i06NAfMjzabZw2OT5IniYM8_xAhAf

# Scores

### Introduction:

This time you will create the data.

***Exercise based on [Chris Albon](http://chrisalbon.com/) work, the credits belong to him.***

### Step 1. Import the necessary libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""### Step 2. Create the DataFrame that should look like the one below."""

data = {"first_name": ["Jason", "Molly", "Tina", "Jake", "Amy"], "last_name": ["Miller", "Jacobson", "Ali", "Miner", "Cooze"], "age": [42, 52, 36, 24, 73], "female": [0, 1, 1, 0, 1], "preTestScore": [4, 24, 31, 2, 3], "postTestScore": [25, 94, 57, 62, 70]}
df = pd.DataFrame(data, columns = ["first_name", "last_name", "age", "female","preTestScore", "postTestScore"])
df

"""### Step 3. Create a Scatterplot of preTestScore and postTestScore, with the size of each point determined by age
#### Hint: Don't forget to place the labels
"""

plt.scatter(df.preTestScore, df.postTestScore, s = df.age)
plt.xlabel("preTestScore")
plt.ylabel("postTestScore")
plt.show()

"""### Step 4. Create a Scatterplot of preTestScore and postTestScore.
### This time the size should be 4.5 times the postTestScore and the color determined by sex
"""

plt.scatter(df.preTestScore, df.postTestScore, s = 4.5 * df.postTestScore, c = df.female)

"""### BONUS: Create your own question and answer it."""

df["postTestScore"].plot(kind = "bar")
df

df["gender"] = df["female"].apply(lambda x: "female" if x ==  1 else "male")
avg = df.groupby("gender")[["age", "preTestScore", "postTestScore"]].mean()
avg.plot(kind = "barh")

