# -*- coding: utf-8 -*-
"""Seanio_SORTING.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uh0d8CCkrpbTtgzh0jY5LGboZAEjJWBu

# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries
"""

import pandas as pd
import numpy as np

"""### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.
"""

url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
chipo = pd.read_csv(url,sep="\t")

"""### Step 4. How many products cost more than $10.00?"""

expensive_items = chipo[chipo['item_price']>10.00]
num_of_exp = expensive_items['item_name'].nunique()
num_of_exp

"""### Step 5. What is the price of each item?
###### print a data frame with only two columns item_name and item_price
"""

item_priceS = chipo[['item_name','item_price']].drop_duplicates()
item_priceS

"""### Step 6. Sort by the name of the item"""

sorted_items = chipo.sort_values('item_name')
sorted_items

"""### Step 7. What was the quantity of the most expensive item ordered?"""

most_exp = chipo.sort_values('item_price', ascending = False).iloc[0]
most_exp['quantity']

"""### Step 8. How many times was a Veggie Salad Bowl ordered?"""

veggie = chipo[chipo['item_name'] =='Veggie Salad Bowl']
veggie['quantity'].sum()

"""### Step 9. How many times did someone order more than one Canned Soda?"""

soda=chipo[(chipo['item_name'] == "Canned Soda") & (chipo['quantity']>1)]
len(soda)

