# -*- coding: utf-8 -*-
"""United States - Crime Rates - 1960 - 2014 Pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x6jGMwz9xLw3MchlN69EPG8Xpz0Oha8O

# United States - Crime Rates - 1960 - 2014

### Introduction:

This time you will create a data

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries
"""

import pandas as pd
import numpy as np

"""### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/US_Crime_Rates/US_Crime_Rates_1960_2014.csv).

### Step 3. Assign it to a variable called crime.
"""

url = "https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/US_Crime_Rates/US_Crime_Rates_1960_2014.csv"
crime = pd.read_csv(url, sep  = ",")

"""### Step 4. What is the type of the columns?"""

type_columne = crime.dtypes
type_columne

"""##### Have you noticed that the type of Year is int64. But pandas has a different type to work with Time Series. Let's see it now.

### Step 5. Convert the type of the column Year to datetime64
"""

crime["Year"] = pd.to_datetime(crime["Year"], format = "%Y")

"""### Step 6. Set the Year column as the index of the dataframe"""

crime = crime.set_index("Year")

"""### Step 7. Delete the Total column"""

crime = crime.drop("Total", axis = 1)

"""### Step 8. Group the year by decades and sum the values

#### Pay attention to the Population column number, summing this column is a mistake
"""

decades = (crime.index.Year //10) *10
total = crime.groupby(decades).agg({"Population": "mean", "Violent": "sum", "Property": "sum", "Murder": "sum", "Forcible_Rape": "sum", "Robery": "sum", "Aggravated_assault": "sum", "Burglary": "sum", "Larceny_Theft": "sum", "Vehicle_Theft": "sum"})

"""### Step 9. What is the most dangerous decade to live in the US?"""

