# -*- coding: utf-8 -*-
"""US - Baby Names Pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dat8K9mbrPtwFBGKy3T0_NxiEeijRvbk

# US - Baby Names

### Introduction:

We are going to use a subset of [US Baby Names](https://www.kaggle.com/kaggle/us-baby-names) from Kaggle.  
In the file it will be names from 2004 until 2014


### Step 1. Import the necessary libraries
"""

import pandas as pd
import numpy as np

"""### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv).

### Step 3. Assign it to a variable called baby_names.
"""

url = "https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv"
baby_names = pd.read_csv(url, sep = ",")

"""### Step 4. See the first 10 entries"""

baby_names.head(10)

"""### Step 5. Delete the column 'Unnamed: 0' and 'Id'"""

baby_names.drop(["Unnamed: 0", "Id"], axis = 1, inplace = True)

"""### Step 6. Is there more male or female names in the dataset?"""

genders = baby_names["Gender"].value_counts()
genders

"""




### Step 7. Group the dataset by name and assign to names"""

names = baby_names.groupby("Name").sum()
names.sort_values("Count", ascending = 0)

"""### Step 8. How many different names exist in the dataset?"""

baby_names["Name"].nunique()

"""### Step 9. What is the name with most occurrences?"""

names.Count.idxmax()

"""### Step 10. How many different names have the least occurrences?"""

names.Count.idxmin()

"""### Step 11. What is the median name occurrence?"""

names.Count.median()

"""### Step 12. What is the standard deviation of names?"""

names.Count.std()

"""### Step 13. Get a summary with the mean, min, max, std and quartiles."""

names.describe()

