# -*- coding: utf-8 -*-
"""Visualizing Chipotle's Data pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qiWLcgIOS1c1fFJ7yJS3_BwNyfZK6w8M

# Visualizing Chipotle's Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
from collections import Counter

# set this so the graphs open internally
# %matplotlib inline

"""### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.
"""

url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
chipo = pd.read_csv(url, sep = "\t")
url2 = "https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/US_Crime_Rates/US_Crime_Rates_1960_2014.csv"
crime = pd.read_csv(url2, sep  = ",")

"""### Step 4. See the first 10 entries"""

chipo.head(10)

"""### Step 5. Create a histogram of the top 5 items bought"""

top_5 = chipo["item_name"].value_counts().head(5)
plt.figure(figsize = (10, 6))
top_5.plot(kind = "bar")
plt.show()

"""### Step 6. Create a scatterplot with the number of items orderered per order price
#### Hint: Price should be in the X-axis and Items ordered in the Y-axis
"""

amount = chipo.groupby("order_id").agg({"quantity": "sum", "item_price": "sum"})
plt.figure(figsize = (10, 6))
plt.scatter(amount["item_price"], amount["quantity"])
plt.show()

"""### Step 7. BONUS: Create a question and a graph to answer your own question."""

price_distribution = crime[["Violent", "Property", "Murder", "Forcible_Rape", "Robbery", "Aggravated_assault", "Burglary", "Larceny_Theft", "Vehicle_Theft"]].value_counts()
plt.figure(figsize = (10, 6))
price_distribution.plot(kind = "bar")
plt.show()

